engines:
  # ... CONFIG CONTENT ...
  phpmd:
    enabled: true
    # ... CONFIG CONTENT ...
    exclude_fingerprints:
    - 18f0603cb59ae513bd8a6981f0aecbfa
    - 303c91ed3c7ee2c7d1bb79d62b682a18
    - 3a66e4409ac67372029fe4264b46a29c
    - 52ca5454edbf05eecd06da162af972d9
    - 252b54aff1b9151122fadd2d807fdfd2
languages:
  PHP: true
exclude_paths:
- "LICENSE"
- "README.md"
- "codecov.yml"
- "composer.json"
- "composer.lock"
- "phpunit.xml"
- "tests-run.sh"
